# Introduction to Scientifc Python

This worksheet gives examples and exercises for the `numpy`, `pandas` and `matplotlib` modules covered in the Scientific Python session. As well as the exercises you can also experiment with any topics you don't feel you understand.

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Numpy

Numpy is the basis of much of the Scientific Python ecosystem. It provides:
* The efficient array structure
* Fine control of numeric types
* Rapid vectorised computations
* Fast numeric function implementations in C, C++ or Fortran

You will usually see it imported as `np`, to save typing. It is usually best to stick to this convention.

In [2]:
import numpy as np

### Arrays
The `np.array` is an ordered data container similar to a list, but where all its members must be the same data type and with the ability to support multiple dimensions. It is created by passing list-like data:

In [3]:
# A 1d array
np.array([1,2,3,4,5])

# A 2d array
np.array([[1,2],
          [3,4]])

# A 3d array
np.array([[[1,2],
           [3,4]],
          [[5,6],
           [7,8]]])

array([1, 2, 3, 4, 5])

array([[1, 2],
       [3, 4]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

An array has an associated data type, which can be accessed using its `dtype` attribute.

In [4]:
x = np.array([1,2,3,4])
x.dtype

dtype('int64')

This defaults to `int64` or `float64` if you give python `int` or `float` values, which means each number uses 64 bits of memory. Sometimes you would prefer to use a different type to save memory or time. See [here](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.types.html) for  a list and description of types. You should take some care when assigning types - using a type with the wrong range leads to errors. **Exercise**: Work out why each of the following result happens:

In [5]:
# Default array
np.array([-512, -256, -128, -64, -32, -16, -8, -4, -2, -1, 0,
          1, 2, 4, 8, 16, 32, 64, 128, 256, 512])

array([-512, -256, -128,  -64,  -32,  -16,   -8,   -4,   -2,   -1,    0,
          1,    2,    4,    8,   16,   32,   64,  128,  256,  512])

In [6]:
# Boolean Array
np.array([-512, -256, -128, -64, -32, -16, -8, -4, -2, -1, 0,
          1, 2, 4, 8, 16, 32, 64, 128, 256, 512], dtype=np.bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [7]:
# Signed 16bit Integer array
np.array([-512, -256, -128, -64, -32, -16, -8, -4, -2, -1, 0,
          1, 2, 4, 8, 16, 32, 64, 128, 256, 512], dtype=np.int16)

array([-512, -256, -128,  -64,  -32,  -16,   -8,   -4,   -2,   -1,    0,
          1,    2,    4,    8,   16,   32,   64,  128,  256,  512],
      dtype=int16)

In [8]:
# Unsigned 16-bit integer array
np.array([-512, -256, -128, -64, -32, -16, -8, -4, -2, -1, 0,
          1, 2, 4, 8, 16, 32, 64, 128, 256, 512], dtype=np.uint16)

array([65024, 65280, 65408, 65472, 65504, 65520, 65528, 65532, 65534,
       65535,     0,     1,     2,     4,     8,    16,    32,    64,
         128,   256,   512], dtype=uint16)

In [9]:
# Signed 8-bit integer array
np.array([-512, -256, -128, -64, -32, -16, -8, -4, -2, -1, 0,
          1, 2, 4, 8, 16, 32, 64, 128, 256, 512], dtype=np.int8)

array([   0,    0, -128,  -64,  -32,  -16,   -8,   -4,   -2,   -1,    0,
          1,    2,    4,    8,   16,   32,   64, -128,    0,    0],
      dtype=int8)

In [10]:
# Unsigned 8-bit integer array
np.array([-512, -256, -128, -64, -32, -16, -8, -4, -2, -1, 0,
          1, 2, 4, 8, 16, 32, 64, 128, 256, 512], dtype=np.uint8)

array([  0,   0, 128, 192, 224, 240, 248, 252, 254, 255,   0,   1,   2,
         4,   8,  16,  32,  64, 128,   0,   0], dtype=uint8)

In [11]:
# Complex array
np.array([-512, -256, -128, -64, -32, -16, -8, -4, -2, -1, 0,
          1, 2, 4, 8, 16, 32, 64, 128, 256, 512], dtype=np.complex64)

array([-512.+0.j, -256.+0.j, -128.+0.j,  -64.+0.j,  -32.+0.j,  -16.+0.j,
         -8.+0.j,   -4.+0.j,   -2.+0.j,   -1.+0.j,    0.+0.j,    1.+0.j,
          2.+0.j,    4.+0.j,    8.+0.j,   16.+0.j,   32.+0.j,   64.+0.j,
        128.+0.j,  256.+0.j,  512.+0.j], dtype=complex64)

Numpy provides functions to create various common arrays easily:
* Zeros
* Ones
* Random numbers (e.g. `np.random.rand` or `np.random.randint`)
* Identity matrices
* Evenly spaced arrays
The first 3 allow creation of arbitary sized arrays, while the latter has only one dimension:

In [12]:
np.zeros(10)
np.ones((2,3))
np.random.randint(10, size=(3,3))
np.identity(3)
np.arange(2, 5, 0.5)
np.linspace(0,10, 4)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[7, 8, 4],
       [8, 1, 6],
       [8, 3, 9]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

You are also able to define the data type of arrays you create:

In [13]:
np.array([1,2,3], dtype=np.float16)
np.zeros((2,2), dtype=np.bool)

array([1., 2., 3.], dtype=float16)

array([[False, False],
       [False, False]])

**Exercise:** Create a 3 dimensional array, consisting of a 4x5 matrix of 0s, a matrix of 1s and a  matrix of random integers between 0 and 1000. Try making the data type np.int8 and np.uint8, what happens?

### Array indexing
Array indexing works similarly to lists, using square brackets. Slicing using the `:` operator allows you to extract sections of the arrays.

In [14]:
x = np.identity(6)
x
x[2,2]
x[1:4, 2:5]

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

1.0

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

If a dimension is ommited it is assumed you want all values from it (equivalent to a bare`:`):

In [15]:
x[3]
x[3,:]
x[:,3]

array([0., 0., 0., 1., 0., 0.])

array([0., 0., 0., 1., 0., 0.])

array([0., 0., 0., 1., 0., 0.])

This makes it possible to index using multiple square brackets, accessing one dimension at a time. However this is much less efficient that using a single pair of brackets.

### Vectorised Opperations
Numpy arrays allow you to apply opperations across all elements in an optimized way, including providing highly optimized versions of various maths functions that act in this manner. This allows you to greatly speed up numerical computations:

In [16]:
x = np.arange(0,10)
x
x + 1
x ** 2
np.sin(x)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

When operating using multiple vectors they are operated on elementwise:

In [17]:
y = np.arange(9,-1,-1)
y
x + y
x * y

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

array([ 0,  8, 14, 18, 20, 20, 18, 14,  8,  0])

If arrays are different sizes they cannot generally be combined. Numpy compares dimension pair sizes and to be compatible they must either be equal or one must be 1 (this is essentially what happens when working with a scalar).

In [18]:
# a (2,1) and a (10,1) vector aren't compatible because 10 != 2
z = np.array([0,1])
x * z

ValueError: operands could not be broadcast together with shapes (10,) (2,) 

In [19]:
# However a (10,1) and a (1,2) vector are
z = np.array([[0],[1]])
x * z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Exercises**: Compute
* $e^x$
* $|x|$
* Add 1 to the 2nd and 4th rows
* Multiply the 2nd and 4th columns by 0

In [21]:
x = np.random.randn(4,5)
x

array([[ 0.22176643, -0.93252534, -0.67212286,  0.97924509, -0.44621279],
       [-1.70320879,  0.3489702 , -0.23839   , -0.60636901, -0.9503763 ],
       [ 0.42498641,  1.23243446,  1.0078204 ,  1.13549314, -0.75356993],
       [-0.25805866,  1.47371413,  1.36102921,  0.21166669,  1.70691753]])

## Pandas

The `pandas` library provides data structures for tabular data and allows you to work with them efficiently. We'll give some examples and exercises for basic use in this session. Further details can be found in the [10 Min Pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html) tutorial and the wider [documentation](http://pandas.pydata.org/pandas-docs/stable/).
As with `numpy` you will usually find `pandas` imported with an abreviation:

In [22]:
import pandas as pd

The basic object in pandas is the `Series`, which is a one dimensional labeled container based upon the numpy array. Like arrays they are ordered and can only have one data type. They are constructed from any ordered container:

In [26]:
s = pd.Series([1,2,3,4,5])
s
s.values
s.index

0    1
1    2
2    3
3    4
4    5
dtype: int64

array([1, 2, 3, 4, 5])

RangeIndex(start=0, stop=5, step=1)

As we can see the series contains a set of values in a numpy array and an index, in this case numbers stored as a `RangeIndex`. The index can also use other labels, such as strings or dates, either by passing a dictionary or using the index argument:

In [40]:
s = pd.Series([1,2,3,4,5], index=('one', 'two', 'three', 'four', 'five'))
s

s = pd.Series({'negative': -1, 'zero':0, 'positive':1})
s

one      1
two      2
three    3
four     4
five     5
dtype: int64

negative   -1
zero        0
positive    1
dtype: int64

negative   -2
zero        0
positive    2
dtype: int64

Series support vectorised calculation in the same way as numpy arrays. **Exercise**: Create a series of random values labeled dates and then calculate their mean and variance (Hint: [date_range](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.date_range.html))

The main data storage object used in pandas is the `DataFrame`, which is a tabular structure whose columns are made up of series with a common index. They are constructed using a dictionary of labeled columns, each of a data type that can be converted into a Series: 

In [39]:
pd.DataFrame({'A':1,
              'B':[1,2,3,4,5],
              'C':pd.Series(['one', 'two', 'three', 'four', 'five'])})

A  B      C
0  1  1    one
1  1  2    two
2  1  3  three
3  1  4   four
4  1  5   five

DataFrames can also be easily loaded from external files using read commands. Here we will import the common iris dataset and examine the first few rows using the `head` method (there is also an equivalent `tail` method):

In [43]:
iris = pd.read_table('iris.tsv', sep='\t')
iris.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

You can also see a quick statistical summary of your results:

In [46]:
iris.describe()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

It is possible to access the Series objects making up columns in two ways:

In [49]:
iris.Petal_Length.head()
iris['Sepal_Width'].head()

0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
Name: Petal_Length, dtype: float64

0    3.5
1    3.0
2    3.2
3    3.1
4    3.6
Name: Sepal_Width, dtype: float64

The DataFrame can also be accessed using the `.loc` and `.iloc` attributes, which allow you to select sections by label and coordinate respectively, using similar syntax to list or array slicing. Note the fact that the two methods still behave differently when the row labels are numbers; `iloc` doesn't include the final index in the range.

In [55]:
iris.loc[1:5, ('Sepal_Length', 'Species')]
iris.iloc[1:5, 3:5]

Sepal_Length Species
1           4.9  setosa
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa
5           5.4  setosa

Petal_Width Species
1          0.2  setosa
2          0.2  setosa
3          0.2  setosa
4          0.2  setosa

It is also possible to access sections of the table based on logical tests, for instance where petals are over a certian length. Note that you must use the bitwise logical operators `&` and `|` instead of the `and` and `or` keywords when combining conditions here, and thus be careful of the order of opperations

In [86]:
iris[iris.Petal_Length > 6]
iris[(iris.Species != 'virginica') & (iris.Sepal_Length > 6.5)]
iris[(iris.Petal_Length > 6.5) | (iris.Sepal_Length > 6.5)]

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
105           7.6          3.0           6.6          2.1  virginica
107           7.3          2.9           6.3          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     Species
50           7.0          3.2           4.7          1.4  versicolor
52           6.9          3.1           4.9          1.5  versicolor
58           6.6          2.9           4.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
86           6.7          3.1           4.7          1.5  versicolor

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     Species
50            7.0          3.2           4.7          1.4  versicolor
52            6.9          3.1           4.9          1.5  versicolor
58            6.6          2.9           4.6          1.3  versicolor
65            6.7          3.1           4.4          1.4  versicolor
75            6.6          3.0           4.4          1.4  versicolor
76            6.8          2.8           4.8          1.4  versicolor
77            6.7          3.0           5.0          1.7  versicolor
86            6.7          3.1           4.7          1.5  versicolor
102           7.1          3.0           5.9          2.1   virginica
105           7.6          3.0           6.6          2.1   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
112           6.8          3.0           5.5          2.1   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
120           6.9          3.2           5.7          2.3   virginica
122           7.7          2.8           6.7          2.0   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
135           7.7          3.0           6.1          2.3   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica

Finally, you are able to modify values and add columns using the same syntax:

In [67]:
test = iris.copy() # note we have to copy the DataFrame otherwise a reference to the same data is passed
test.loc[0, 'Species'] = 'not setosa'
test.iloc[0, 1] = 100
test['height'] = np.random.randint(10, size=len(test))
test.head()

Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     Species  height
0           5.1        100.0           1.4          0.2  not setosa       7
1           4.9          3.0           1.4          0.2      setosa       2
2           4.7          3.2           1.3          0.2      setosa       2
3           4.6          3.1           1.5          0.2      setosa       8
4           5.0          3.6           1.4          0.2      setosa       6

**Exercises**:
* Add a column for the area of sepals and petals. Hint: petals are roughly elipsis shaped
* Add some random heights to the main `iris` data
* Calculate the mean petal and sepal area for seach of the three species (use `iris.species.unique()`)

## Matplotlib